# Custom Language File for Launcher Customizer

[ejs.app]
title = "El Desván ✨"

[ejs.landing]
mediaGitHubURL = "https://desvan.zergiv2.tech/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ruBdk64sPD"

[ejs.settings]
sourceGithubLink = "https://github.com/Zergiv/ElDesvan"
supportLink = "https://github.com/Zergiv/ElDesvan/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido"
welcomeDescription = "Launcher de El Desván ✨"
welcomeDescCTA = "Estás a solo unos clicks de entrar."
